### ISSUE TITLE
과제 질문있습니다.

### ISSUE THREAD

**Issue by Cho-Hyun-Ji** [CNUCOM/compilers_CNU_2022#11]
질문 1)
Hul{
	Hul?
} 2
Hul{
	Hul>
} 3
과 같이 중첩이 아니라 하나의 반복문이 끝난 뒤에 새로운 반복문이 오는 경우도 고려해야 할까요?

질문 2)
입력이 파일명으로 들어오나요? 예를 들면, test.hul을 제가 콘솔에서 입력해야 하는 것인지, 아니면 "./test.hul" 을 코드 안에 넣으면 될지 궁금합니다.

**Comment by Masterwhiece** [comment]
질문 1) 네
질문 2) 코드에 넣으면 됩니다.
