### ISSUE TITLE
과제1 상대경로 이용하시길 바랍니다. 절대경로 이용하지 마세요.

### ISSUE THREAD

**Issue by Masterwhiece** [CNUCOM/compilers_CNU_2022#12]
파일 입출력 경로에서, 절대경로 사용하지 마시고, 상대경로로 작성해주시길 바랍니다.
.java와 같은 디렉토리에서 입력 파일, 출력 파일 다루면 된다고 말씀드렸으므로 ./test.hul ./test.c로 작성하시면 됩니다.

**절대경로 예시**
`C:/Users/youjeong/workspace/test.hul`
**상대경로 예시**
`./test.hul`

**Comment by YoungChyHa** [comment]
HulMain.java 등의 소스코드 파일이 src 폴더 내부에 들어가야 동작하는데
text.hul , test.c는 src 폴더 밖에 넣어야 하나요? 아니면 안에 넣어야 하나요?

**Comment by Masterwhiece** [comment]
그게 아마 IDE에서 돌아가게 하기 위해서 그렇게 짜야하는 것으로 알고 있습니다.
테스트할 때는 그렇게 해보시고, 제출할 때에는 위에서 안내한대로 경로를 작성해서 제출해주시기 바랍니다.

**Comment by Masterwhiece** [comment]
_걱정하시는 분들을 위하여_
본인 컴퓨터에서 실행시킬 때 어떤 폴더에 입력 파일을 넣는지는 상관 없습니다. 그리고 테스트해볼 때 경로와 파일 위치는 자유롭게 작성해서 해보시고, 제출할 때만 ./test.hul ./test.c 경로로 내주시면 됩니다.
전체 학생들의 코드를 자동으로 채점하기 위함입니다.
