### ISSUE TITLE
실행파일은 무엇인가요?

### ISSUE THREAD

**Issue by YoungChyHa** [CNUCOM/compilers_CNU_2022#14]
과제 1 설명란에 소스코드와 실행파일을 제출하라고 되어 있는데 실행 파일이 무엇인지 잘 모르겠습니다.

**Comment by Masterwhiece** [comment]
이후에 드린 과제설명 자료를 바탕으로 9/8 수업 때 설명드렸는데요, 실행파일은 필요 없고
.java 확장자의 소스파일만 제출하면 됩니다.
