### ISSUE TITLE
과제 2 질문있습니다.

### ISSUE THREAD

**Issue by hanhyeonuk** [CNUCOM/compilers_CNU_2022#16]
ide설치와 jar파일 연동하고 테스트 자바파일을 만들어서 실행을 하면 아래와 같은 오류가 뜹니다. 혹시 제가 무엇을 잘못한 것인지 [알수있을까요?

오류: 기본 클래스 TestMiniGo을(를) 초기화할 수 없습니다.
원인: java.lang.NoClassDefFoundError: org/antlr/v4/runtime/CharStream

**Comment by hanhyeonuk** [comment]
해결했습니다. jar파일 포함이 충돌났던 문제였습니다.

**Comment by BaekMinHyeon** [comment]
저도 같은 오류가 나서 그런데 혹시 어떻게 해결하였는지 알려주실수 있으신가요??

**Comment by Dragonfri** [comment]
혹시 조금 더 자세히 설명 가능한가요? 저도 같은 오류 걸렸는데 해결을 못하겠네요
