### ISSUE TITLE
과제 2 질문있습니다.

### ISSUE THREAD

**Issue by green-study** [CNUCOM/compilers_CNU_2022#17]
환경설정 완료 후 실행해본 결과 Go 코드 내의 세미콜론에 대하여 오류가 발생하는 것을 알게 되었습니다.
오류가 뜨긴 하지만 출력은 정상적으로 나옵니다.
과제 설명 도중 세미콜론이 Go 코드에서 파싱 오류를 막기위해 필요하다고 말씀해주신 것도 같은데, 
제가 놓친 부분이 있는 지 궁금합니다.
오류부분을 무시하고 아래 출력만 정상적으로 된다면 상관없는 것인가요?
![image](https://user-images.githubusercontent.com/70996958/190390438-76f6e069-4db3-4f6d-8101-0d01be2efed8.png)

**Comment by PLASLaboratory** [comment]
추가로 test.go로 인한 에러는 크게 신경쓰지 않으셔도 됩니다. 
사이버 캠퍼스에 에러가 나지 않는 test.go파일을 몇개 더 추가하였습니다. 

무엇보다 에러가 안나는 방향으로 test.go파일을 직접 수정해보시면서 MiniGo.g4파일의 문법을 이해하시는 것이 좋아요

**Comment by green-study** [comment]
넵 감사합니다
