### ISSUE TITLE
과제 1번 학생분들 어떻게 푸셨나요?

### ISSUE THREAD

**Issue by downpool** [CNUCOM/compilers_CNU_2022#23]
제 접근 방식을 
단계별로 나누면

0) 정적 리스트, 변수 생성
    
1) 입력 받기

2) 받은 입력 값들을 토큰으로 쪼개고(공백으로 구분), switch-case 구문을 이용한 함수를 실행 
    2 - 1) 구조 [func tokens(tk: String) -> Void]
    2 - 2) 각 입력받은 값에 따른 코드블럭을 실행함.
    2 - 3) 실행한 코드블럭의 결과값을 임시 리스트에 잠시 저장해둔다.
    + ⍺
3) 입력받은 값이 이상이 없는지.
    ex1) 들여쓰기가 잘 작동하는지,
    ex2) 반복문을 중첩할시, 와 반복문을 연속해서 사용할 시를 구분할수 있는지
    확인한다.
4) 새로운 함수를 정의하여 빈칸을 넣어준다

5) 순서대로 출력할 파일에 쓴다.

**Comment by downpool** [comment]
다른 접근 방법 있으면 추천 부탁드립니다!

**Comment by Tabbygray** [comment]
제대로 된 프로그램 만드는 경험이 많지 않아서 중구난방으로 만들긴 했는데, 큰 개괄은 비슷한것 같습니다.
1. 입력받기
2. 토큰 나눠서 읽은 뒤, 순서에 맞게 버퍼에 써내려가기
(getToken 함수에서 공백은 모조리 스킵, 문자로 시작하면 문자,숫자,언더바 외 문자가 나올때까지 읽기. 
그 뒤 키워드 테이블과 비교하여 키워드인지 확인. 숫자로 시작하면 숫자토큰으로 처리)
3. 버퍼 출력

괄호 반복시행은 재귀로 처리했는데 들여쓰기랑 숫자랑 여기저기 꼬여서 그냥 엉성하게 처리해서 낸것 같습니다...
