### ISSUE TITLE
과제 2 질문있습니다.

### ISSUE THREAD

**Issue by Ja-efan** [CNUCOM/compilers_CNU_2022#24]
ANTLR 설치 및 설정까지 완료하고 main함수 있는 파일을 run 했을 때 결과는 정상적으로 나오는데,
아래와 같은 에러가 뜹니다. 혹시 해결 방법을 알 수 있을까요.
ANTLR Tool version 4.10.1 used for code generation does not match the current runtime version 4.11.1
ANTLR Tool version 4.10.1 used for code generation does not match the current runtime version 4.11.1

**Comment by jdongyun** [comment]
https://www.antlr.org/download/antlr-4.10.1-complete.jar
이 버전으로 받아주시면 될 것 같습니다.
