### ISSUE TITLE
Eclipse에 Antlr4를 설치하는 과정에서 문제가 발생했습니다.

### ISSUE THREAD

**Issue by Deuter-2O** [CNUCOM/compilers_CNU_2022#25]
![ant](https://user-images.githubusercontent.com/112850031/190846158-396541c8-4117-4f18-bf99-25a0ca935542.jpg)

Project - Properties에서 Java Build Path를 찾을 수 없습니다.
어디서 찾을 수 있나요?

**Comment by CNUCOM** [comment]
Eclipse 버전, Java 버전, ANTLR 버전 얼마쓰나요?

**Comment by Deuter-2O** [comment]
Eclipse 2022-06 (4.24.0)
Java 17
Antler 4 IDE 0.3.6
입니다.

**Comment by CNUCOM** [comment]
지금 보여준 프로퍼티 창에서 "Property Nature"-"Add를 누르시고
"Eclipse Faceted Project Properties"와 "Java"를 추가해보세요.
그리고 한번 더 시도해보시기 바랍니다.

**Comment by Deuter-2O** [comment]
![image](https://user-images.githubusercontent.com/112850031/190857327-aba6a734-2725-4821-8725-75edc4dbfe05.png)
Project Structure에 접근하여 MiniGoLexer.java 및 MiniGoParser.java를 불러오는 과정에서 막혔습니다...

이클립스에서는 file 메뉴에 Project Structure 메뉴가 존재하지 않습니다

**Comment by CNUCOM** [comment]
이건 path 문제인 것 같은데 다른 사람들이 도와주면 좋을 것 같습니다.

**Comment by Deuter-2O** [comment]
6시간동안 해결 중인데 진전이 없습니다
import를 사용하면 인식하지 못하고 에러가 늘어나기만 합니다

**Comment by SongJungHyun1004** [comment]
프로젝트 Properties - Java Build Path - Source - Add Folder - target - generated-sources - antlr4파일 체크 하시면 해결되는 것 같습니다.

**Comment by Deuter-2O** [comment]
다른 방법으로 해결했습니다.

**Comment by sebin-Cheon** [comment]
혹시 어떻게 해결됐는지 알려주실 수 있나요?

**Comment by Deuter-2O** [comment]
antlr4 폴더 하위의 소스 파일을 전부 복사해서 패키지에 붙여넣기하는 다소 무식한 방법인데
나중에 다시 시도해보니 윗분이 알려주신 방법도 동작하더라고요
2가지가 있는데 후자가 좀더 정석적인 답 같습니다
