### ISSUE TITLE
2차 과제 출력 질문 있습니다.

### ISSUE THREAD

**Issue by Deuter-2O** [CNUCOM/compilers_CNU_2022#27]
![image](https://user-images.githubusercontent.com/112850031/190886127-23bf71e4-bdc3-4a0a-9536-83fc38705250.png)

Go 언어의 특성상 세미콜론을 인식하지 못하여 에러를 반환합니다.
그래서 Rule 2-1과 2-2를 출력하는데 난향을 겪고 있습니다.

1. 정해진 형식이나 순서대로 출력해야 하나요? 그렇다면 그것은 무엇인가요?
2. 그렇지 않다면 모든 Rule을 출력해야 하나요?
3. 그렇다면 Rule 2-1이나 2-2는 어떻게 출력해야 하나요?

**Comment by PLASLaboratory** [comment]
정해진 형식이나 답은 없습니다. 
마찬가지로 모든 룰을 출력해야한다거나, 하는 제약사항은 없습니다. 

다만, 앞으로의 과제를 위해 MiniGo.g4의 문법을 반드시 이해하고 그에 맞는 test.go를 작성할 수 있어야합니다. 
그리고 여러분들 질문 답변 받은 이슈는 closed하지 말아주세요:)
