### ISSUE TITLE
2주차 과제 질문입니다.

### ISSUE THREAD

**Issue by Jeongminseok2** [CNUCOM/compilers_CNU_2022#30]
![image](https://user-images.githubusercontent.com/37893103/190910860-67f9a3be-9c53-403d-a8ac-168f37627506.png)
![image](https://user-images.githubusercontent.com/37893103/190910869-6116de8a-9e70-4936-85b2-1b4af69d5c27.png)
![image](https://user-images.githubusercontent.com/37893103/190910877-ffd678b4-86de-41c5-981b-8fe4ed50535b.png)
![image](https://user-images.githubusercontent.com/37893103/190910913-7a7a0401-d9b2-468d-8219-afd521f16263.png)

Project Properties에서 라이브러리 추가할 수 있는 Java Build Path 항목이 없습니다

**Comment by CanSJun** [comment]
프로젝트 -> Properties -> Project Natures -> Add -> Java 추가 하시면 됩니다.

**Comment by Jeongminseok2** [comment]
감사합니다 👍
