### ISSUE TITLE
2주차 과제 질문있습니다

### ISSUE THREAD

**Issue by SunghyoBaek** [CNUCOM/compilers_CNU_2022#36]
![image](https://user-images.githubusercontent.com/23161044/191338230-80b6c146-d01d-4c97-9b10-5e3aed325848.png)

왼쪽 위 사진처럼 MiniGo.g4 파일 47~49번 라인에 

각각 "The word 'var'/'func'/'int' is not correctly spelled" 오류가 있습니다. 

오른쪽 위 사진은 MiniGo.tokens 파일인데 찾아보니 57, 61, 70 라인에도 마찬가지로 'var', 'int', 'func' 에만 오류가 있습니다.

왼쪽 아래는 현재 프로젝트이고, 오른쪽 아래는 ANTLR 설치 영상에 있는 gen 폴더를 캡쳐한 사진입니다.

혹시 제 프로젝트에는 영상에 있는 MiniGo.interp, MiniGoBaseVisitor, MiniGoLexer.interp, MiniGoVisitor.java 이 없어서

오류가 발생하는 것인지, 아니면 다른 이유 때문인지 질문드립니다.

**Comment by PLASLaboratory** [comment]
g4파일의 작성된 내용으로 인한 에러는 무시하셔도됩니다. 
제 생각에는 현재 다른 패키지에 있는 .java파일을 찾지 못하는 것 같은데, 같은 패키지로 생성된 소스코드를 옮기거나 import를 하셔야할 것 같습니다.

**Comment by SunghyoBaek** [comment]
감사합니다
