### ISSUE TITLE
2주차 과제 출력 질문있습니다.

### ISSUE THREAD

**Issue by woou4578** [CNUCOM/compilers_CNU_2022#37]
![image](https://user-images.githubusercontent.com/73514027/191382015-a66ab30c-f03e-4390-aeb3-6682a87a5de5.png)
Main은 알려주신 그대로 작성하였고,

![image](https://user-images.githubusercontent.com/73514027/191381680-70007dfc-db9b-485f-bc01-c6f03ef193c0.png)
MiniGo.g4 파일에서 system.out.println 이쪽 입력을 어떻게 바꾸든, test.go의 파일을 바꾸든 출력문이 202200000 Rule 0 한줄로만 나옵니다.
이상해서 antlr 재설치도 해보고 여러번 test.go 내용도 바꿔가며 해봤는데도 
출력문이 한줄로만 나옵니다. 
심지어 아무것도 안하고 맨처음 상태에서 program의 system출력만 바꿔도 똑같습니다
202200000 Rule 0 한 줄이 고정 값으로 나오는데
왜 고정 값으로만 출력이 되는지 궁금합니다.

**Comment by PLASLaboratory** [comment]
g4 파일을 수정하고 새로 구문분석기를 재생성해보셨을까요?

만약 해도 안된다면 다시 말씀해주시기 바랍니다.

**Comment by woou4578** [comment]
해결되었습니다. 감사합니다
