### ISSUE TITLE
2주차 과제 관련 질문 드립니다.

### ISSUE THREAD

**Issue by aabccde** [CNUCOM/compilers_CNU_2022#38]
1. 완성된 jar 파일을 실행하면 아래와 같이 ANTLR Tool의 버전과 current runtime version이 다르다는 문구가 뜨는데 이것은 무시해도 되나요?
<img width="605" alt="image" src="https://user-images.githubusercontent.com/112850083/191393132-dbece569-4db6-4ef8-b875-7f8fa75d3f12.png">

2. 과제를 실행하는 모습을 촬영하여 제출하라고 하셨는데, TestMiniGo.java 파일을 IDE에서 실행시키는 장면만 영상으로 남겨 찍으면 되나요?

3.  만약 2번 질문이 맞다면, 제가 만든 test.go 파일이 아닌 조교님께서 배포 해주신 test.go파일들로 실행하는 장면을 영상으로 남겨도 되나요?

**Comment by PLASLaboratory** [comment]
1, jar 파일을 내라는 말이 있는데, 무시하셔도 됩니다. 
2, 넵
3, 자유롭게 하셔도 괜찮습니다.

**Comment by aabccde** [comment]
그렇다면 java project는 제출하지 않고, 보고서만 제출하면 되나요?

**Comment by PLASLaboratory** [comment]
자바 프로젝트도 함께 제출해주세요

**Comment by aabccde** [comment]
1. 그럼 자바 프로젝트와 보고서를 제출하되 보고서는 과제_설명.pdf에 나와있는 양식대로 작성하면 되나요? 

2. IDE에서 실행했을 때에도 첫 번째 질문에서 나온 문구가 나오는데 무시해도 상관 없나요?

**Comment by PLASLaboratory** [comment]
1. 네
2. 네 괜찮습니다

**Comment by aabccde** [comment]
넵. 답변 감사합니다!
