### ISSUE TITLE
자바 프로젝트도 함께 제출해주세요

### ISSUE THREAD

**Issue by PLASLaboratory** [CNUCOM/compilers_CNU_2022#39]
과제 제출 시 자바 프로젝트도 함께 제출해주세요

_Originally posted by @PLASLaboratory in https://github.com/CNUCOM/compilers_CNU_2022/issues/38#issuecomment-1253102027_

**Comment by PLASLaboratory** [comment]
jar는 제출하지 않으셔도 됩니다

**Comment by fspull** [comment]
TA님 메일 알려주실수 있나요??

**Comment by KimSu-Been** [comment]
메일은 어디에 나와있나요? 올려주신 자료에는 없는 것 같아서요.

**Comment by Blackcows** [comment]
저도 공지를 늦게 봐서 프로젝트 파일을 제출을 못했는데
혹시 계정 프로필에 나와있는 이메일로 보내드리면 되는지 여쭤보고 싶습니다

**Comment by PLASLaboratory** [comment]
bnm961126@gmail.com 입니다:)
