### ISSUE TITLE
Class Problem 풀이한거 맞춰보실분 구해요 

### ISSUE THREAD

**Issue by Tabbygray** [CNUCOM/compilers_CNU_2022#4]
20-2
 다음을 나타내는 정규표현식을 작성해보시오. 단, 정규표현식 작성이 불가능 한 것이 있다면 추측하는 이유를 적어보시오.
 1.  a로 시작하는 식별자 
 2.  2진수중 4의 배수
 3.  식별자중 a와 b의 갯수가 동일하게 나타나는 것

20-3 
 다음 정규 표현식을 인식하는 유한상태오토마타를 상태전이도로 표현하시오.
 ab
 a|b 
 a*
 a+
 a+c
 ((a+c)|x)*

20-5 
 다음 정규표현식들의 차이는?
 1. [abc] 와 abc
 2. [^abc] 와 [abc^]와 ^abc
 3. [a-z] 와 [-az]와 [az-]
 4. [a|b] 와 (a|b)

**Comment by Tabbygray** [comment]
20-2
1>> a[a-zA-Z0-9]
2>> (1(1|0)*)*100
3>> 불가능하다.

20-3 https://ibb.co/jfHMstB

20-4
1>> [abc] 는 a or b or c , abc는 abc
2>> [^abc]는 a와 b와 c를 제외한 모든 문자 하나, [abc^]는 a or b or c or "^", ^abc는 라인의 시작에 abc
3>> [a-z]는 영어 소문자 , [-az]는 "-" or a or z , [az-]도 마찬가지.
4>> [a|b]는 a or "|" or b , (a|b)는 a or b

**Comment by Masterwhiece** [comment]
와~ 정말 잘 한 것 같습니다.
20-2-1 혹시 다르게 생각한 사람 있을까요?

**Comment by kingseungwooya** [comment]
감사합니다.  혹시 FSA ((a+c)|x)* 올려주실 수 있으신가요? 링크가 만료되어 확인이 안됩니다.

**Comment by Tabbygray** [comment]
> 감사합니다. 혹시 FSA ((a+c)|x)* 올려주실 수 있으신가요? 링크가 만료되어 확인이 안됩니다.

https://ibb.co/dmtWyX7
다시 올렸습니다.

**Comment by kingseungwooya** [comment]
> > 감사합니다. 혹시 FSA ((a+c)|x)* 올려주실 수 있으신가요? 링크가 만료되어 확인이 안됩니다.
> 
> 
> 
> https://ibb.co/dmtWyX7
> 
> 다시 올렸습니다. 

확인했습니다 감사합니다!!!
