### ISSUE TITLE
3주차 과제 질문있습니다.

### ISSUE THREAD

**Issue by DonOhhhh** [CNUCOM/compilers_CNU_2022#40]
혹시 과제3 관련 test.go와 g4파일과 수정된 과제설명 파일은 언제쯤 올려주시나요?
그리고 전달해주신 과제관련 유튜브 영상이 삭제되었다고 나오는데 다른 링크는 없나요?

**Comment by KimSu-Been** [comment]
3주차에 영상은 있습니다

**Comment by DonOhhhh** [comment]
https://youtu.be/vXsmZjoYCRw 이거 아닌가요? 이거 삭제됐다고 나오는데..

**Comment by PLASLaboratory** [comment]
네, 회차관리에 보시면 영상업로드 되어있습니다.

**Comment by DonOhhhh** [comment]
6주차 영상은 10월 6일부터 볼 수 있게 되어있는데 과제는 10월 5일까지입니다. 혹시 영상기간을 조정해주실 수 있나요?

**Comment by PLASLaboratory** [comment]
영상 기간 조정하였습니다.

**Comment by DonOhhhh** [comment]
@PLASLaboratory 영상 기간 조정이 안 되어 있습니다. 다시 한번 확인해주실 수 있나요?
