### ISSUE TITLE
3주차 과제에서 CharStreams를 인식하지 못한다고 나옵니다

### ISSUE THREAD

**Issue by Deuter-2O** [CNUCOM/compilers_CNU_2022#41]
![에러1](https://user-images.githubusercontent.com/112850031/191889877-f1ee40d7-6cd6-4b9f-aa60-990d9ee859d2.jpg)

**Comment by PLASLaboratory** [comment]
이렇게만 봐서는 무엇이 문제인지 잘 모르겠는데요.... 음 .. ANTLR가 연결이 잘 되어있는지 확인해보실래요?

**Comment by Deuter-2O** [comment]
어떻게 확인하나요?

**Comment by PLASLaboratory** [comment]
https://mainia.tistory.com/2273

라이브러리 연결 하셨는지 확인해보세요.

**Comment by Deuter-2O** [comment]
![image](https://user-images.githubusercontent.com/112850031/191917153-93c6e789-bdec-40db-869d-2751bdcdc83f.png)
연결되어 있는데도 인식하지 못합니다

**Comment by CNUCOM** [comment]
antlr 버전을 4.4 쓰시네요. CharStreams가 새로 나온 거라서 antlr 버전 4.7 이상만 되는 것 같습니다.
이전 것은 ``` new ANTLRFileStream("myinputfile")``` 이렇게 쓰라는 것 같습니다.
(https://www.antlr.org/api/Java/org/antlr/v4/runtime/CharStreams.html)

아니면 4.7로 버전업 하셔도 좋을 것 같습니다.
