### ISSUE TITLE
3주차 과제 파일 관련해서 질문있습니다.

### ISSUE THREAD

**Issue by YJR999** [CNUCOM/compilers_CNU_2022#42]
올려 주신 영상에도 과제에도 MiniC 파일은 없는데 어디에 있는지 알 수 있을까요?

**Comment by PLASLaboratory** [comment]
올려드린 영상은 작년 과제를 기준으로 올려드린 것입니다. 그래서 그냥 참고용으로만 보시면 됩니다. 이번 과제에서는 miniC는 사용하지 않습니다.
