### ISSUE TITLE
3주차 Pretty Print  과제 관련 공지

### ISSUE THREAD

**Issue by PLASLaboratory** [CNUCOM/compilers_CNU_2022#43]
3주차 과제 기한은 과제 유인물에 적힌 것과는 다르게 **10월 5일까지**입니다.

작년에 과제 설명해드린 영상자료를 lms에 업로드해두었습니다.
작년 기준으로 설명이 되어 있어서 사용하는 문법이 다릅니다. 
하지만 listener api를 활용하는 방법은 동일하기 때문에 영상 보시고 참고하시면 좋을 것 같습니다.

그리고 go 예제는 이번 주말 중으로 올려드리겠습니다.
구현 관련해서는, 입력을 별 다른 처리 없이 그대로 string으로 출력하는 것 먼저 해보시길 추천드립니다.
먼저 그대로 출력 먼저 하시고, 이후에 pretty print 스타일을 추가하시는 것이 편하실겁니다.

그리고 질문 이슈 올리시고, 라벨 설정 꼭 해주세요.
"질문" 라벨과 "hw_?th" 라벨 등을 잘 활용해주세요.

**Comment by DonOhhhh** [comment]
@PLASLaboratory LMS에 과제 설명영상이 6주차에 업로드 되어있는건 확인했는데 학습가능기간이 10월 6일부터입니다. 혹시 조정해주실 수 있나요?

**Comment by SeoyeonKang** [comment]
라벨은 권한이 필요하다고 합니다.... 그냥 라벨 없이 올려주세요..
