### ISSUE TITLE
혹시 라벨 어떻게 다는지 알려주실 수 있나요?

### ISSUE THREAD

**Issue by DonOhhhh** [CNUCOM/compilers_CNU_2022#45]
아마 권한이 없어서 labels 옆에 톱니바퀴 모양이 안 떠서 라벨을 달 수가 없는데 따로 labels를 다는 방법이 있나요?

**Comment by fcmonoid** [comment]
권한을 드려야하는데... 일단 그냥 올려주시기 바랍니다.

**Comment by CNUCOM** [comment]
권한을 드려야하는데... 일단 그냥 올려주시기 바랍니다.

**Comment by PLASLaboratory** [comment]
따로 이슈 관리자가 있어서 레이블은 신경 쓰지 않으셔도 될 것 같습니다.

**Comment by Masterwhiece** [comment]
제가 이슈 레이블 관리합니다!
