### ISSUE TITLE
3주차 과제 질문있습니다.

### ISSUE THREAD

**Issue by positiveWand** [CNUCOM/compilers_CNU_2022#46]
3주차 과제 관련 질문 드립니다.
과제와 함께 제공된 pdf에서 제시된 예시 중 test2.go가 처리된 내용을 보면 세미콜론으로 문장이 끝나면 다음 문장은 다음 줄에서 시작하도록 처리하였는데 과제에서 요구한 pretty print에서는 이와 같은 규칙이 없습니다.

이것은 과제 기준과는 상관없이 별도로 보기좋도록 처리한 것일까요 아니면 pretty print 규칙의 일부일까요?

![image](https://user-images.githubusercontent.com/49838556/191960361-d2d49bbf-6fae-4946-9fa0-981219efc338.png)
(위의 그림과 같이 변수 선언문들이 각각 다른 줄에 배치되도록 처리됐습니다)

**Comment by SeoyeonKang** [comment]
pretty print 규칙 맞습니다. 한 줄에 명령 하나만 오도록 해주세요. 
일반적으로 코딩하는 스타일+pretty print 규칙으로 보기 좋게 출력한다고 생각해주시면 됩니다.

-TA
