### ISSUE TITLE
e-leaning 사이트 과제 제출을 열어주면 감사하겠습니다

### ISSUE THREAD

**Issue by yrrho2** [CNUCOM/compilers_CNU_2022#5]
e-leaning 사이트 과제 제출을 열어주면 감사하겠습니다.

**Comment by CNUCOM** [comment]
지금 준비 중인데, 제출 파일 종류나 테스트 파일  경로, 보고서 항목 등 세부적으로 조정 중이라, 수업 중에 언급했다시피 목요일에 여는 것이 좋을 것 같습니다. 양해 부탁합니다.

**Comment by yrrho2** [comment]
네 답변 감사합니다.
