### ISSUE TITLE
3주차 과제 질문

### ISSUE THREAD

**Issue by jdongyun** [CNUCOM/compilers_CNU_2022#53]
MiniGo.g4 파일에 정의된 `IDENT '(' args ')'` 부분이 정상적으로 동작하지 않는 것 같습니다.
`func()` 이나 `func(1, 2)`와 같이 argument의 개수가 0 또는 2 이상이면 정상적으로 동작하는데,
`func(1)`과 같이 argument의 개수가 1개이면 정상 동작하지 않는 것 같습니다.

**Comment by PLASLaboratory** [comment]
함수 호출은 아직 구현되어있지 않습니다.
