### ISSUE TITLE
[질문] 3주차과제

### ISSUE THREAD

**Issue by hanhyeonuk** [CNUCOM/compilers_CNU_2022#58]
3주차 과제 ugly 예제 1번은 if (조건식) 2번은 if 조건식 처럼 소괄호가 있고 없고로 둘로 나뉘어져 있는데, 둘 다 맞는 문법인건가요?

**Comment by SeoyeonKang** [comment]
네 맞습니다. antlr로 파싱에만 문제가 없으면 됩니다.

-TA
