### ISSUE TITLE
[질문] 파싱테이블에 대한 질문

### ISSUE THREAD

**Issue by KimSu-Been** [CNUCOM/compilers_CNU_2022#59]
Class problem의 문제를 풀어보면 $를 유도 할 수 없는데, 이럴 때는 어떻게 해야할 지 궁금합니다.  그냥 비워주면 되는건가요?
![image](https://user-images.githubusercontent.com/89886506/193193739-fdba0a96-1b35-4d2d-bf95-5f9193146979.png)
![image](https://user-images.githubusercontent.com/89886506/193193755-d2dda6ed-3565-4f9f-a9a8-57121b02107b.png)

**Comment by CNUCOM** [comment]
네, 좋은 질문입니다. $에 대한 것이 없으면 안 그리셔도 됩니다. 예를 들어 만약  ```S->null``` 과 같은 식이 있다고 가정하면, $일 때 선택되는 규칙일 것이고, 그 때는 $ 열을 만드시면 됩니다. (주로, 입력은 비었는데, 스택은 덜 비워진 경우)
