### ISSUE TITLE
[질문] Pretty Print 과제에서 enter###는 언제 쓰는 건가요? 

### ISSUE THREAD

**Issue by Tabbygray** [CNUCOM/compilers_CNU_2022#61]
3주차 과제를 방향성 없이 진행하다보니 ExitParam, ExitStmt... 등등 Exit 에서만 구현을 하게 되는데요, 
과제의 결과는 나오긴 하는데, 방향을 잘못 잡은 것인지 Enter 함수들을 쓸 일이 없습니다.
Enter 함수들은 쓸 일이 언제인지 모르겠습니다.

**Comment by SeoyeonKang** [comment]
이번 과제에서는 enter 관련 함수는 크게 쓸 일이 없긴 합니다. 구현 방향에 따라 다르기 때문에 enter 메소드를 쓰지 않는다고 잘못된 것은 아닙니다.    쓰게 된다면 indent 구현할 때 depth를 count하거나 할 때 쓸 수 있습니다.
