### ISSUE TITLE
10월 24일 월요일 5시에 수업하는것이 맞을까요?

### ISSUE THREAD

**Issue by Cho-Hyun-Ji** [CNUCOM/compilers_CNU_2022#65]
월요일 5시~6시에 수업이 있는데, 시험 기간인 10월 24일 월요일도 동일할까요?
다른 과목의 시험 일정 조정 때문에 다른 교수님께서 다시 한 번 확인 부탁하셨습니다.

![image](https://user-images.githubusercontent.com/104757451/194977035-b9e06ab0-332e-44e9-b6f5-1bfe4e7b4d95.png)

**Comment by Masterwhiece** [comment]
24일 모각공 수업은 정상적으로 진행합니다.
교수님께 따로 문의하시기 바랍니다.
