### ISSUE TITLE
Regex 를 CFG로 바꾸는 문제 질문

### ISSUE THREAD

**Issue by Dragonfri** [CNUCOM/compilers_CNU_2022#69]
![SmartSelect_20221018-101614_Chrome](https://user-images.githubusercontent.com/37804008/196312617-cbcf13f3-77c9-473b-8bea-b0870ca29152.jpg)

이해가 안되서 챶아보니 예시에 저런식으로 적혀있더라고요.

대체로 S로 시작하던데 3번 문제의 경우 X로 시작한 이유가 있을까요? 그냥 XY 깔맞춤하고 싶어서 인가요 아니면 제가 모르는 다른 뜻이 있는 건가요?

그리고
(시작문자) -> (빈 문자) 
이 표현은 유한 오토마타에서 쌍원 같이 끝을 의미하는건가요? 그럼 무조건 들어가줘야하는 문법인가요?

**Comment by Tabbygray** [comment]
1. 시작심벌은 주로 맨 처음에 lhs에 나타나는 것을 지칭하며, S거나 X거나는 큰 상관 없는것으로 알고있습니다.
2. 빈 문자가 ε을 얘기하시는 거라면 이는 Nonterminal이 empty(빈 문자)로 유도될 수 있다는 뜻이며, FSM에서 필수적인 쌍원이라고 말하긴 애매합니다. ε없이도 끝애 도달하는 예시가 있기 떄문입니다. 
![FSM1](https://user-images.githubusercontent.com/28866016/196407514-7af1c22e-980c-4f7e-86b0-7aba8122584d.png)
[ε 가 없는 FSM의 예]
![FSM2](https://user-images.githubusercontent.com/28866016/196407529-57d1f719-2c2e-447f-8bc9-aec9148c841a.png)
[ε 가 있는 FSM의 예]

**Comment by Jeongminseok2** [comment]
위에 2번인 (a+b)*에 대한 솔루션에 있어서 질문이 있습니다.
해당 CFG에서는 S -> bS , S -> null 로 가면 "b"가 생성됩니다.
그런데 RE에서는 "b" 를 생성할 수 없으므로 잘못된 CFG 아닌가에 대해 궁금합니다.
추가로 제가 생각하는 CFG는 S -> AbS | null , A -> Aa | a 입니다.
