### ISSUE TITLE
기말고사 일정 및 장소 재조정하고 공지하겠습니다.

### ISSUE THREAD

**Issue by Masterwhiece** [CNUCOM/compilers_CNU_2022#70]
일정 : 12/14 (수) 7시~8시30분
장소 : 공5 410호(00분반), 411호(01분반)

부득이한 사정으로 참가가 불가능한 경우, therealmaria@naver.com으로 메일 주세요.

**Comment by Tabbygray** [comment]
다른 과목 기말고사 일정과 겹치는데, 메일드리면 될까요?

**Comment by Masterwhiece** [comment]
@Tabbygray 네!

**Comment by Masterwhiece** [comment]
소프트웨어공학 기말고사와 일정이 겹친 관계로 일정 재조정 후 공지 드리겠습니다.

메일 이제 안주셔도 됩니다. 감사합니다.
