### ISSUE TITLE
과제4 질문입니다.

### ISSUE THREAD

**Issue by yountaeseop** [CNUCOM/compilers_CNU_2022#84]
![image](https://user-images.githubusercontent.com/85738697/200250765-ced60424-7463-44dd-918e-d32ae6c79d8d.png)

Test.j파일을 만들로 jar파일이 있는 위치에 넣은다음 명령어로 클래스까지 만들어줬는데
java Test할때 오류가 나옵니다. 어떻게 해결할 수 있을까요.. Test.j파일은 과제파일에 있는 어셈블리어 코드
그대로 복붙했습니다.

**Comment by CNUCOM** [comment]
https://github.com/CNUCOM/compilers_CNU_2022/issues/76#issue-1434065524
참고해보시기 바랍니다!
