### ISSUE TITLE
과제5 제출 파일과 (ㄱ)손으로 작성하는 범위 문의

### ISSUE THREAD

**Issue by Cho-Hyun-Ji** [CNUCOM/compilers_CNU_2022#88]
1. 제출해야 할 파일이 보고서 하나 인가요 아니면 보고서와 Sum.j 이렇게 두 가지 인가요?

2. (ㄱ)을 손으로 작성하여 제출할 때 sum 함수만 쓰면 될까요? 아니면 클래스 전체를 써야 하나요?

**Comment by PLASLaboratory** [comment]
1. 제출은 보고서만 제출하시면 됩니다. 
보고서에는 수기 작성한 코드 전체와 설명, 해당 코드를 Sum.j 파일로 만들어서 jasmin을 이용하여 실행한 결과화면 캡쳐본이 포함되어야 합니다.

2. 코드 전체를 작성해주셔야 합니다. 전체 코드를 작성하셔야 해당 코드를 Sum.j로 만들어서 실행할 때 문제없이 동작합니다.
