### ISSUE TITLE
과제 관련 질문드립니다.

### ISSUE THREAD

**Issue by aabccde** [CNUCOM/compilers_CNU_2022#9]
Hul? 함수로 입력 받은 값을 변수에 저장하기 전에 Hul!, Hul>, Hul<과 같은 함수들이 나올 수 있는 상황도 고려하여 프로그램을 만들어야 하나요?

**Comment by CNUCOM** [comment]
그건 오류이므로, 과제를 할 때에는 고려하지 않으셔도 됩니다.

**Comment by aabccde** [comment]
답변 감사합니다.
