### ISSUE TITLE
3주차 모범답안은 언제 제공되나요?

### ISSUE THREAD

**Issue by Deuter-2O** [CNUCOM/compilers_CNU_2022#91]
6주차 과제 실행시 제공해주신다고 한 것 같은데 찾아봐도 없길래 질문합니다

**Comment by PLASLaboratory** [comment]
안녕하세요.

사실 스켈레톤 코드와 유사하여 생략한 것이긴 한데, 요청주셔서 공유해 드립니다.
전체 코드를 공개하려던 계획은 없었던지라 일부만 공개하는 점 양해바랍니다.

https://github.com/CNUCOM/compilers_CNU_2022/blob/main/MiniGoPrintListener.java
